export const AUTHORS_LINKS = [
    [
        "https://www.facebook.com/1",
        "https://twitter.com/1",
        "https://www.instagram.com/1",
        "https://www.linkedin.com/1",
    ],
    [
        "https://www.facebook.com/2",
        "https://twitter.com/2",
        "https://www.instagram.com/2",
        "https://www.linkedin.com/2",
    ],
    [
        "https://www.facebook.com/3",
        "https://twitter.com/3",
        "https://www.instagram.com/3",
        "https://www.linkedin.com/3",
    ],
    [
        "https://www.facebook.com/4",
        "https://twitter.com/4",
        "https://www.instagram.com/4",
        "https://www.linkedin.com/4",
    ],
    [
        "https://www.facebook.com/5",
        "https://twitter.com/5",
        "https://www.instagram.com/5",
        "https://www.linkedin.com/5",
    ],
    [
        "https://www.facebook.com/6",
        "https://twitter.com/6",
        "https://www.instagram.com/6",
        "https://www.linkedin.com/6",
    ],
    [
        "https://www.facebook.com/7",
        "https://twitter.com/7",
        "https://www.instagram.com/7",
        "https://www.linkedin.com/7",
    ],
    [
        "https://www.facebook.com/8",
        "https://twitter.com/8",
        "https://www.instagram.com/8",
        "https://www.linkedin.com/8",
    ],
];
